# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - textsummarizer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://textsummaizer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_73a4a6e8b6a84ca4baa0d6dea382e769 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_24baceba3d6a47f19934f26be7d31112 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: textsummaizer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_73a4a6e8b6a84ca4baa0d6dea382e769 }}/textsummarizer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'textsummarizer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ccfc153317524d01b9fae65d76a045b9 }}
        images: 'textsummaizer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_73a4a6e8b6a84ca4baa0d6dea382e769 }}/textsummarizer:${{ github.sha }}'